source("game_mechanics.r")
source("interface.r")
source("sbot.r")
source("bot.r")
source("neural.r")
source("nbot.r")


conf=rep(0,9)
turn=1
strat=1:9
rcd=NULL



###############
## neural network bot:
###############


botnn=ntrain(n=200,nn=botnn,players=c("s","r")) 

###############
## frequentist bot:
###############

learn_matrix=read.lm()  #file="learn_matrix.dat" generated by write.lm()
stat.lm()

learn_matrix=train(n=100, players=c("s","s"))

learn_matrix=train(n=100,players=c("m","s"))

learn_matrix=train(n=100,players=c("s","m"))

learn_matrix=train(n=100,players=c("m","m"))

stat.lm()


##  after match with human learn with higher weight:
##  learn_matrix=learn(wt=2)
##  TODO: allow varying weight  

write.lm()




